server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user1-service
          uri: lb://user1-service
          predicates:
            - Path=/user1/**
        - id: contact1-service
          uri: lb://contact1-service
          predicates:
            - Path=/contact1/**
        
